name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
    steps:
          - name: 'Checkout Code'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build and Push frontend Image'
            run: |
              docker build --build-arg NEXT_PUBLIC_WS_URL=/ws --build-arg NEXT_PUBLIC_API_URL=/api -f app.dockerfile --tag ghcr.io/${{github.actor}}/perplexica-frontend:latest .
              docker push ghcr.io/${{github.actor}}/perplexica-frontend:latest

          - name: 'Build and Push backend Image'
            run: |
              docker build -f backend.dockerfile --tag ghcr.io/${{github.actor}}/perplexica-backend:latest .
              docker push ghcr.io/${{github.actor}}/perplexica-backend:latest
